import {actor,staff,allRecords,getRecord,db,insert,change,audit,text,amount,AppError,errorResponse,visible,clientRecord,RecordRow} from '@/lib/crm-server';
const allowedTypes=new Set(['proposal','invoice','contract','onboarding','deliverable','milestone','message','change','hub','service','time','expense','article','member','settings','task','ticket','subscription','template','project','update','resource']);
function documentTotal(p:Record<string,any>){const lines=Array.isArray(p.lineItems)?p.lineItems:[];if(!lines.length||lines.length>100)throw new AppError('Add between 1 and 100 line items');const subtotal=lines.reduce((sum:number,l:any)=>{if(!text(l.description)||!Number.isFinite(Number(l.quantity))||Number(l.quantity)<=0||Number(l.quantity)>10000)throw new AppError('Check line descriptions and quantities');return sum+Math.round(Number(l.quantity)*amount(l.rate))},0);const discountPence=amount(p.discountPence||0);if(discountPence>subtotal)throw new AppError('Discount cannot exceed subtotal');const taxRate=Number(p.taxRate||0);if(!Number.isFinite(taxRate)||taxRate<0||taxRate>100)throw new AppError('Check tax percentage');const taxPence=Math.round((subtotal-discountPence)*taxRate/100);return {lineItems:lines,subtotal,discountPence,taxPence,taxRate,total:subtotal-discountPence+taxPence}}
export async function GET(request:Request){try{const a=await actor();const rows=await allRecords();if(a.role==='contributor')return Response.json({actor:a,records:rows.filter(r=>['task','ticket'].includes(r.type)&&r.payload.owner===a.email)});if(a.role!=='client')return Response.json({actor:a,records:rows});if(!a.clientId)throw new AppError('Client account is not linked',403);return Response.json({actor:a,records:rows.filter(r=>visible(r,a.clientId!)).map(clientRecord)});}catch(e){return errorResponse(e)}}
export async function POST(request:Request){try{
 const a=await actor(),b=await request.json() as Record<string,any>,action=text(b.action,80),now=new Date().toISOString();
 const manager=()=>{if(!['owner','manager'].includes(a.role))throw new AppError('Manager permission required',403)};
 if(a.role==='contributor'&&action!=='status')throw new AppError('Contributors can update only their assigned work',403);
 if(action==='importClients'){
  manager();if(!Array.isArray(b.clients)||!b.clients.length||b.clients.length>500)throw new AppError('Import between 1 and 500 clients');const existing=await allRecords(),emails=new Set(existing.filter(r=>r.type==='client').map(r=>text(r.payload.email).toLowerCase()).filter(Boolean));const ops=[];for(const item of b.clients){const name=text(item.name,200),email=text(item.email,250).toLowerCase();if(!name)throw new AppError('Every client needs a name');if(email&&emails.has(email))continue;if(email)emails.add(email);ops.push(insert({id:crypto.randomUUID(),type:'client',name,status:'active',payload:{email,contact:text(item.contact,200),phone:text(item.phone,80),industry:text(item.industry,200),source:'Import'}}));}if(ops.length)await db().batch([...ops,audit(a,`Imported ${ops.length} clients`,'client-import')]);return Response.json({count:ops.length});
 }
 if(action==='save'){
  manager();if(!allowedTypes.has(b.type))throw new AppError('Unsupported record type');if(b.type==='member'&&a.role!=='owner')throw new AppError('Only the owner manages access',403);
  const name=text(b.name,200);if(!name)throw new AppError('Add a title');const old=b.id?await getRecord(b.id):null;if(old&&old.type!==b.type)throw new AppError('Record type cannot change');
  if(old&&['accepted','signed','paid'].includes(old.status)&&['proposal','contract','invoice'].includes(old.type))throw new AppError('Accepted and signed documents are locked. Create a new version.');
  const p={...(old?.payload||{}),...(b.payload||{})};if(b.type==='member'){p.email=text(p.email).toLowerCase();if(!p.email.includes('@')||!['manager','contributor','client'].includes(p.role))throw new AppError('Add an email and role');if(p.role==='client'&&!b.clientId)throw new AppError('Choose a client');}
  let value=amount(b.value??old?.value??0);if(['proposal','invoice'].includes(b.type)){const totals=documentTotal(p);Object.assign(p,totals);value=totals.total;p.issueDate=p.issueDate||now.slice(0,10);if(b.type==='invoice'){p.paid=old?.payload.paid||0;if(value<p.paid)throw new AppError('Invoice cannot be less than recorded payments');}}
  if(b.type==='time'){p.minutes=amount(p.minutes);p.hourlyRate=amount(p.hourlyRate||0)}
  if(b.type==='contract'&&old?.payload.publishedBody){p.publishedBody=old.payload.publishedBody;p.documentHash=old.payload.documentHash;}
  if(b.type==='member'){const duplicate=(await allRecords()).find(r=>r.type==='member'&&r.id!==old?.id&&r.payload.email===p.email&&r.status!=='archived');if(duplicate)throw new AppError('This email already has an access assignment');}
  if(b.clientId){const client=await getRecord(b.clientId);if(client.type!=='client')throw new AppError('Choose a valid client');}
  if(p.projectId){const project=await getRecord(p.projectId);if(project.type!=='project'||project.clientId!==(b.clientId||null))throw new AppError('Project and client must match');}
  const record={id:old?.id||crypto.randomUUID(),type:b.type,name,clientId:b.clientId||null,status:old?.status||(['member','service','settings','time','expense','article'].includes(b.type)?'active':['task','ticket','onboarding','milestone'].includes(b.type)?'open':'draft'),value,payload:p};
  await db().batch([old?change(old,record):insert(record),audit(a,`${old?'Updated':'Created'} ${b.type}: ${name}`,record.id,record.clientId)]);return Response.json({id:record.id});
 }
 if(action==='comment'||action==='ticket'){
  const target=await getRecord(text(b.target));if(a.role==='client'&&(!a.clientId||!visible(target,a.clientId)))throw new AppError('Record unavailable',404);
  const body=text(b.body);if(!body)throw new AppError('Add a message');const id=crypto.randomUUID();await db().batch([insert({id,type:action==='ticket'?'ticket':'message',name:action==='ticket'?text(b.name,200)||'Support request':`Message on ${target.name}`,clientId:target.clientId,status:'open',payload:{projectId:target.type==='project'?target.id:target.payload.projectId,targetId:target.id,body,author:a.name,visible:a.role==='client'||b.visible===true}}),audit(a,action==='ticket'?'Support request created':'Comment added',target.id,target.clientId)]);return Response.json({id});
 }
 if(action==='requestChange'){
  const project=await getRecord(text(b.id));if(project.type!=='project'||(a.role==='client'&&(!a.clientId||!visible(project,a.clientId))))throw new AppError('Project unavailable',404);const body=text(b.body);if(!body)throw new AppError('Describe the requested change');const id=crypto.randomUUID();await db().batch([insert({id,type:'change',name:text(b.name,200)||body.slice(0,80),clientId:project.clientId,status:'requested',payload:{projectId:project.id,body,visible:true,author:a.name}}),audit(a,'Requested scope change',id,project.clientId)]);return Response.json({id});
 }
 const r=await getRecord(text(b.id));const client=a.role==='client';if(client&&(!a.clientId||!visible(r,a.clientId)))throw new AppError('Record unavailable',404);
 if(action==='newVersion'){
  manager();if(!['proposal','contract','deliverable','hub'].includes(r.type))throw new AppError('This record does not support versions');const id=crypto.randomUUID();const p:Record<string,any>={...r.payload,version:Number(r.payload.version||1)+1,previousVersion:r.id,visible:false};for(const key of ['signedBy','signedAt','signerId','signerEmail','consent','documentHash','publishedBody','acceptedAt','acceptedBy','clientDecision','decidedAt','decidedBy'])delete p[key];await db().batch([insert({...r,id,name:`${r.name} · revision`,status:'draft',payload:p}),audit(a,'Created a new document version',id,r.clientId)]);return Response.json({id});
 }
 if(action==='publish'){
  manager();if(!r.clientId)throw new AppError('Assign a client before publishing');if(['accepted','signed'].includes(r.status))throw new AppError('This document is already final');let p:any={visible:true,publishedAt:now};
  if(r.type==='contract'){const terms=text(r.payload.body);if(!terms)throw new AppError('Add contract terms first');const clientRecord=await getRecord(r.clientId);const project=r.payload.projectId?await getRecord(r.payload.projectId):null;const body=`${r.name}\nClient: ${clientRecord.name}\nAgreed fee: GBP ${(r.value/100).toFixed(2)}\n\nScope\n${project?.payload.scope||r.payload.scope||'See agreed proposal'}\n\nTerms\n${terms}`;p.publishedBody=body;p.documentHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
  await db().batch([change(r,{status:['proposal','contract','invoice'].includes(r.type)?'sent':['deliverable','change','hub','milestone'].includes(r.type)?'review':r.status,payload:p}),audit(a,`Published ${r.type}`,r.id,r.clientId)]);return Response.json({ok:true});
 }
 if(action==='acceptProposal'){
  if(r.type!=='proposal'||!['sent','accepted'].includes(r.status))throw new AppError('Publish the proposal before acceptance');if(!client)throw new AppError('Acceptance must come from the assigned client',403);
  const projectId=`project-${r.id}`,contractId=`contract-${r.id}`,onboardId=`onboarding-${r.id}`;
  const prepared=(await allRecords()).filter(x=>[projectId,onboardId].includes(x.id));
  await db().batch([...prepared.map(x=>change(x,{payload:{visible:true}})),change(r,{status:'accepted',payload:{acceptedBy:a.name,acceptedAt:now,projectId}}),insert({id:projectId,type:'project',name:r.name,clientId:r.clientId,status:'onboarding',value:r.value,payload:{visible:true,proposalId:r.id,scope:r.payload.scope,progress:0,nextMilestone:'Complete onboarding and contract'}}),insert({id:contractId,type:'contract',name:`Agreement · ${r.name}`,clientId:r.clientId,status:'draft',value:r.value,payload:{projectId,proposalId:r.id,body:r.payload.terms||'',visible:false}}),insert({id:onboardId,type:'onboarding',name:`Discovery · ${r.name}`,clientId:r.clientId,status:'open',payload:{projectId,visible:true,questions:['What does success look like?','Who is your audience?','Which services and deliverables are essential?','What is your target launch date?','Who will approve the work?','Please share your brand references and existing assets.'],answers:{}}}),audit(a,'Proposal accepted; project and onboarding created',r.id,r.clientId)]);return Response.json({projectId});
 }
 if(action==='startProject'){
  manager();if(r.type!=='proposal')throw new AppError('Select a proposal');const projectId=`project-${r.id}`;
  await db().batch([change(r,{payload:{projectId}}),insert({id:projectId,type:'project',name:r.name,clientId:r.clientId,status:'onboarding',value:r.value,payload:{visible:false,proposalId:r.id,scope:r.payload.scope,nextMilestone:'Proposal acceptance'}}),insert({id:`contract-${r.id}`,type:'contract',name:`Agreement · ${r.name}`,clientId:r.clientId,value:r.value,payload:{projectId,body:r.payload.terms||'',visible:false}}),insert({id:`onboarding-${r.id}`,type:'onboarding',name:`Discovery · ${r.name}`,clientId:r.clientId,status:'open',payload:{projectId,visible:false,questions:['Business goals','Audience','Deliverables','Deadline','Decision maker','Brand references'],answers:{}}}),audit(a,'Prepared linked project, contract and onboarding',r.id,r.clientId)]);return Response.json({projectId});
 }
 if(action==='sign'){
  if(!client)throw new AppError('Only the assigned client can sign',403);if(r.type!=='contract'||r.status!=='sent'||!r.payload.documentHash)throw new AppError('Contract is not ready for signature');if(b.consent!==true||!text(b.signedBy,200))throw new AppError('Your full name and explicit agreement are required');
  await db().batch([change(r,{status:'signed',payload:{signedBy:text(b.signedBy,200),signedAt:now,signerId:a.id,signerEmail:a.email,consent:true,userAgent:request.headers.get('user-agent')||'',ip:request.headers.get('cf-connecting-ip')||''}}),audit(a,'Contract signed',r.id,r.clientId)]);return Response.json({ok:true});
 }
 if(action==='submitIntake'){
  if(r.type!=='onboarding')throw new AppError('Select an onboarding form');if(!client)manager();const answers=b.answers;if(!answers||typeof answers!=='object'||Array.isArray(answers))throw new AppError('Complete the form');const questions=Array.isArray(r.payload.questions)?r.payload.questions:[];if(questions.some((q:string)=>!text(answers[q])))throw new AppError('Complete each question');await db().batch([change(r,{status:'complete',payload:{answers,submittedBy:a.name,submittedAt:now}}),audit(a,'Onboarding submitted',r.id,r.clientId)]);return Response.json({ok:true});
 }
 if(action==='milestoneInvoices'){
  manager();if(r.type!=='project'||!r.clientId)throw new AppError('Choose a client project');const percent=Number(b.depositPercent??50);if(!Number.isInteger(percent)||percent<1||percent>99)throw new AppError('Deposit must be 1–99%');const deposit=Math.round(r.value*percent/100),balance=r.value-deposit,settings=(await allRecords()).find(x=>x.type==='settings');
  await db().batch([insert({id:`deposit-${r.id}`,type:'invoice',name:`DEP-${r.id.replace('project-','').slice(0,8).toUpperCase()}`,clientId:r.clientId,status:'draft',value:deposit,payload:{projectId:r.id,issueDate:now.slice(0,10),dueDate:text(b.dueDate),paid:0,visible:false,description:`${percent}% deposit`,lineItems:[{description:`${r.name} · ${percent}% deposit`,quantity:1,rate:deposit}],paymentInstructions:settings?.payload.paymentInstructions||''}}),insert({id:`balance-${r.id}`,type:'invoice',name:`BAL-${r.id.replace('project-','').slice(0,8).toUpperCase()}`,clientId:r.clientId,status:'draft',value:balance,payload:{projectId:r.id,issueDate:now.slice(0,10),paid:0,visible:false,description:'Final balance',lineItems:[{description:`${r.name} · final balance`,quantity:1,rate:balance}],paymentInstructions:settings?.payload.paymentInstructions||''}}),audit(a,'Created deposit and final-balance invoices',r.id,r.clientId)]);return Response.json({ok:true});
 }
 if(action==='payment'){
  manager();if(r.type!=='invoice'||['void','archived'].includes(r.status))throw new AppError('Choose a valid invoice');const paid=amount(b.paid);if(paid>r.value)throw new AppError('Payment cannot exceed invoice total');await db().batch([change(r,{status:paid===r.value?'paid':paid?'part-paid':r.status,payload:{paid,paymentDate:text(b.paymentDate)||now.slice(0,10),paymentReference:text(b.reference),receipt:paid?`Receipt: ${r.name}; recorded payment ${paid/100} GBP; ${now.slice(0,10)}`:''}}),audit(a,`Recorded total payments of £${(paid/100).toFixed(2)}`,r.id,r.clientId)]);return Response.json({ok:true});
 }
 if(action==='decision'){
  if(!client)throw new AppError('The assigned client must record this decision',403);if(!['deliverable','change','milestone','hub'].includes(r.type)||!['review','changes-requested'].includes(r.status))throw new AppError('This item is not ready for review');if(!['approved','changes-requested'].includes(b.decision))throw new AppError('Choose a decision');
  const ops=[change(r,{status:b.decision,payload:{clientDecision:b.decision,reason:text(b.reason),decidedBy:a.name,decidedAt:now}}),audit(a,`${r.type} ${b.decision}`,r.id,r.clientId)];
  if(r.type==='change'&&b.decision==='approved'){ops.push(insert({id:`change-task-${r.id}`,type:'task',name:r.name,clientId:r.clientId,status:'open',payload:{projectId:r.payload.projectId,notes:r.payload.body,changeId:r.id}}));if(r.value)ops.push(insert({id:`change-invoice-${r.id}`,type:'invoice',name:`CHG-${r.id.slice(0,8).toUpperCase()}`,clientId:r.clientId,status:'draft',value:r.value,payload:{projectId:r.payload.projectId,issueDate:now.slice(0,10),paid:0,visible:false,lineItems:[{description:r.name,quantity:1,rate:r.value}]}}))}
  await db().batch(ops);return Response.json({ok:true});
 }
 if(action==='status'){
  if(client)throw new AppError('Staff access required',403);if(a.role==='contributor'&&(!['task','ticket'].includes(r.type)||r.payload.owner!==a.email))throw new AppError('You can update only assigned tasks or tickets',403);
  const status=text(b.status,40);if(!['open','in-progress','blocked','complete','waiting','resolved','active','paused','cancelled','archived','strategy','design','development','review','launch'].includes(status))throw new AppError('Invalid status');
  if(r.type==='member'&&a.role!=='owner')throw new AppError('Only the owner manages access',403);
  if(['proposal','contract','invoice','audit'].includes(r.type))throw new AppError('Use the dedicated document action');
  if(r.type==='task'&&status==='complete'&&r.payload.dependency){const dependency=await getRecord(r.payload.dependency);if(dependency.status!=='complete')throw new AppError('Complete the preceding task first');}
  if(r.type==='project'&&status==='complete'){const related=(await allRecords()).filter(x=>x.payload.projectId===r.id&&x.status!=='archived');if(!related.some(x=>x.type==='contract'&&x.status==='signed'))throw new AppError('A signed agreement is required before handover');if(related.some(x=>x.type==='invoice'&&x.status!=='void'&&Number(x.payload.paid||0)<x.value))throw new AppError('Settle project invoices before handover');if(related.some(x=>x.type==='task'&&x.status!=='complete')||related.some(x=>x.type==='deliverable'&&x.status!=='approved'))throw new AppError('Complete tasks and obtain deliverable approvals before handover');}
  const ops=[change(r,{status}),audit(a,`Status changed to ${status}`,r.id,r.clientId)];
  if(r.type==='task'&&status==='complete'&&r.status!=='complete'&&[1,7,30].includes(Number(r.payload.recurrenceDays))){const date=new Date(r.payload.due||now);date.setUTCDate(date.getUTCDate()+Number(r.payload.recurrenceDays));ops.push(insert({id:`next-${r.id}`,type:'task',name:r.name,clientId:r.clientId,status:'open',payload:{...r.payload,due:date.toISOString().slice(0,10),previousTask:r.id,dependency:''}}));}
  await db().batch(ops);return Response.json({ok:true});
 }
 if(action==='renewalInvoice'){
  manager();if(r.type!=='subscription'||r.status!=='active')throw new AppError('Choose an active subscription');const date=text(b.period,10);if(!/^\d{4}-\d{2}$/.test(date))throw new AppError('Choose billing month');await db().batch([insert({id:`renewal-${r.id}-${date}`,type:'invoice',name:`RET-${date}-${r.id.slice(0,6).toUpperCase()}`,clientId:r.clientId,status:'draft',value:r.value,payload:{subscriptionId:r.id,issueDate:now.slice(0,10),paid:0,visible:false,lineItems:[{description:`${r.name} · ${date}`,quantity:1,rate:r.value}]}}),audit(a,`Generated ${date} retainer invoice`,r.id,r.clientId)]);return Response.json({ok:true});
 }
 throw new AppError('Unknown action');
}catch(e){return errorResponse(e)}}
