"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { toast } from "sonner";

type Row = {id:string;type:string;name:string;clientId:string|null;status:string;value:number;payload:Record<string,unknown>;createdAt:string;updatedAt:string};
export function Operations({records,createRecord,updateRecord}:{records:Row[];createRecord:(r:Partial<Row>)=>Promise<void>;updateRecord:(id:string,r:Partial<Row>)=>Promise<void>}) {
  const [kind,setKind]=useState("task"),[name,setName]=useState(""),[client,setClient]=useState("none"),[notes,setNotes]=useState(""),[due,setDue]=useState(""),[busy,setBusy]=useState(false);
  const kinds:Record<string,string>={task:"Task",onboarding:"Onboarding checklist item",contract:"Contract register",update:"Client update"};
  async function save(){if(!name.trim())return toast.error("Add a title");setBusy(true);try{await createRecord({type:kind,name,clientId:client==="none"?null:client,status:"open",payload:{notes,due,owner:"Kunle"}});setName("");setNotes("");toast.success("Saved");}catch{toast.error("Could not save; your input has been retained");}finally{setBusy(false)}}
  const rows=records.filter(r=>r.type===kind);
  return <div className="grid gap-6 xl:grid-cols-[340px_1fr]"><section className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Delivery desk</h2><label className="grid gap-2 text-sm">Record type<Select value={kind} onValueChange={setKind}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(kinds).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-2 text-sm">Title<Input value={name} onChange={e=>setName(e.target.value)}/></label><label className="grid gap-2 text-sm">Client<Select value={client} onValueChange={setClient}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Unassigned</SelectItem>{records.filter(r=>r.type==="client").map(r=><SelectItem key={r.id} value={r.id}>{r.name}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-2 text-sm">Due date<Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label className="grid gap-2 text-sm">Notes / document reference<Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><Button disabled={busy} onClick={()=>void save()}>{busy?"Saving…":"Save record"}</Button><p className="text-sm text-slate-500">Internal records only. Contract entries do not collect signatures. Client updates can be copied for delivery; nothing is sent automatically.</p></section><section className="space-y-3"><h2 className="text-xl font-semibold">{kinds[kind]}s</h2>{!rows.length&&<p className="rounded-2xl border bg-white p-6 text-slate-500">No records yet. Add the first one using the form.</p>}{rows.map(r=><article key={r.id} className="space-y-3 rounded-2xl border bg-white p-5"><div className="flex justify-between gap-4"><h3 className="font-semibold">{r.name}</h3><span className="text-sm">{r.status}</span></div><p className="text-sm text-slate-500">{records.find(c=>c.id===r.clientId)?.name||"Unassigned"} · {String(r.payload.due||"No due date")}</p><p className="whitespace-pre-wrap">{String(r.payload.notes||"")}</p><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void updateRecord(r.id,{status:r.status==="complete"?"open":"complete"}).catch(()=>toast.error("Update failed"))}>{r.status==="complete"?"Reopen":"Mark complete"}</Button>{kind==="update"&&<Button variant="outline" onClick={()=>void navigator.clipboard.writeText(r.name+"\n\n"+String(r.payload.notes||"")).then(()=>toast.success("Update copied")).catch(()=>toast.error("Clipboard unavailable"))}>Copy update</Button>}</div></article>)}</section></div>
}
