"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Pick,Row} from './studio';
import {toast} from 'sonner';
type R=Row&{payload:Record<string,any>};
const gbp=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n/100);
export function Planner({records,run,onOpen}:{records:R[];run:(b:Record<string,unknown>)=>Promise<any>;onOpen:(r:R)=>void}){
 const [view,setView]=useState('Board'),[owner,setOwner]=useState('all'),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[query,setQuery]=useState('');const tasks=records.filter(r=>['task','milestone'].includes(r.type)&&(owner==='all'||r.payload.owner===owner)&&r.name.toLowerCase().includes(query.toLowerCase())),owners=Array.from(new Set(tasks.map(r=>r.payload.owner).filter(Boolean))) as string[];
 const days=Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()},(_,i)=>`${month}-${String(i+1).padStart(2,'0')}`);
 return <section className="mb-8"><div className="section-top"><Tabs value={view} onValueChange={setView}><TabsList><TabsTrigger value="Board">Board</TabsTrigger><TabsTrigger value="Calendar">Calendar</TabsTrigger><TabsTrigger value="Workload">Workload</TabsTrigger></TabsList></Tabs><Input className="max-w-64" placeholder="Find a task…" value={query} onChange={e=>setQuery(e.target.value)}/><Pick label="Assignee" value={owner} onChange={setOwner} options={[{value:'all',label:'Everyone'},...owners.map(v=>({value:v,label:v}))]}/></div>{view==='Board'&&<div className="task-board">{['open','in-progress','blocked','complete'].map(status=><section className="task-column" key={status}><h3>{status.replace('-',' ')} <span className="count">{tasks.filter(r=>r.status===status).length}</span></h3>{tasks.filter(r=>r.status===status).map(r=><article key={r.id} className="task-card"><button className="text-left w-full" onClick={()=>onOpen(r)}>{r.name}</button><p className="muted text-sm my-3">{r.payload.owner||'Unassigned'}<br/>{r.payload.due||'No deadline'}</p><Pick label="Move to" value={r.status} onChange={async v=>{try{await run({action:'status',id:r.id,status:v})}catch{}}} options={['open','in-progress','blocked','complete'].map(v=>({value:v,label:v.replace('-',' ')}))}/></article>)}</section>)}</div>}{view==='Calendar'&&<><label className="form-field max-w-64 mb-5">Month<Input type="month" value={month} onChange={e=>setMonth(e.target.value||new Date().toISOString().slice(0,7))}/></label><div className="calendar-grid">{days.map(date=><div className="calendar-day" key={date}><span>{new Date(date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short',day:'numeric'})}</span>{tasks.filter(r=>r.payload.due===date).map(r=><button key={r.id} onClick={()=>onOpen(r)}>{r.name}</button>)}</div>)}</div></>}{view==='Workload'&&<div className="panel">{[...owners,'Unassigned'].map(o=>{const assigned=tasks.filter(r=>(r.payload.owner||'Unassigned')===o);return <div className="linked-row" key={o}><span>{o}</span><span>{assigned.filter(r=>r.status!=='complete').length} open · {assigned.filter(r=>r.status==='complete').length} complete</span></div>})}</div>}</section>
}
export function Reports({records}:{records:R[]}){
 const [from,setFrom]=useState(''),[to,setTo]=useState('');const filtered=records.filter(r=>(!from||r.createdAt.slice(0,10)>=from)&&(!to||r.createdAt.slice(0,10)<=to)),clients=records.filter(r=>r.type==='client'),invoices=filtered.filter(r=>r.type==='invoice'&&r.status!=='void'),leads=filtered.filter(r=>r.type==='lead'),today=new Date().toISOString().slice(0,10),overdue=invoices.filter(r=>r.payload.dueDate&&r.payload.dueDate<today&&(r.payload.paid||0)<r.value);
 return <div className="space-y-5 mb-8"><div className="form-grid max-w-xl"><label className="form-field">Created from<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="form-field">Created to<Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="profit-grid">{[{label:'Invoiced',value:gbp(invoices.reduce((s,r)=>s+r.value,0))},{label:'Recorded receipts',value:gbp(invoices.reduce((s,r)=>s+Number(r.payload.paid||0),0))},{label:'Overdue balance',value:gbp(overdue.reduce((s,r)=>s+r.value-Number(r.payload.paid||0),0))},{label:'Lead conversion',value:leads.length?`${Math.round(leads.filter(r=>r.status==='won').length/leads.length*100)}%`:'No leads'}].map(x=><section className="panel" key={x.label}><p className="muted text-sm">{x.label}</p><p className="text-3xl mt-4">{x.value}</p></section>)}</div><section className="panel"><h2>Revenue by client</h2>{clients.map(c=>{const rows=invoices.filter(r=>r.clientId===c.id);return <div className="linked-row" key={c.id}><strong>{c.name}</strong><span>{gbp(rows.reduce((s,r)=>s+r.value,0))} invoiced · {gbp(rows.reduce((s,r)=>s+Number(r.payload.paid||0),0))} received</span></div>})}</section><section className="panel"><h2>Invoice ageing</h2>{['1–30 days','31–60 days','61–90 days','90+ days'].map((label,i)=>{const rows=overdue.filter(r=>{const age=Math.floor((Date.now()-new Date(r.payload.dueDate).getTime())/86400000);return age>i*30&&(i===3||age<=(i+1)*30)});return <div className="linked-row" key={label}><span>{label} · {rows.length} invoices</span><strong>{gbp(rows.reduce((s,r)=>s+r.value-Number(r.payload.paid||0),0))}</strong></div>})}</section></div>
}
function parseCSV(csv:string){const rows:string[][]=[];let row:string[]=[],value='',quoted=false;for(let i=0;i<csv.length;i++){const c=csv[i];if(c==='"'){if(quoted&&csv[i+1]==='"'){value+='"';i++}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&csv[i+1]==='\n')i++;row.push(value);if(row.some(Boolean))rows.push(row);row=[];value=''}else value+=c;}if(quoted)throw Error('Unclosed quote in CSV');row.push(value);if(row.some(Boolean))rows.push(row);const headers=rows.shift()?.map(s=>s.trim().toLowerCase())||[];if(!headers.includes('name'))throw Error('The CSV needs a name column');return rows.map(row=>Object.fromEntries(headers.map((h,i)=>[h,row[i]||''])))}
export function ClientImport({run}:{run:(b:Record<string,unknown>)=>Promise<any>}){const [csv,setCSV]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Record<string,string>[]>([]);return <section className="panel max-w-3xl mb-8"><h2>Import client contacts</h2><p className="muted my-4">CSV columns: name, email, contact, phone, industry. Existing email addresses are skipped. Up to 500 clients per import.</p><label className="form-field">Choose CSV<Input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>1024*1024)return toast.error('Choose a CSV under 1 MB');setCSV(await f.text());setPreview([])}}}/></label><label className="form-field mt-4">CSV content<Textarea rows={8} value={csv} onChange={e=>{setCSV(e.target.value);setPreview([])}}/></label><Button className="my-4" variant="outline" onClick={()=>{try{setPreview(parseCSV(csv))}catch(e){toast.error((e as Error).message)}}}>Review import</Button>{preview.length>0&&<><p className="mb-3">{preview.length} contacts found</p>{preview.slice(0,5).map((r,i)=><div className="linked-row" key={i}><span>{r.name}</span><span>{r.email}</span></div>)}<Button className="mt-4" disabled={busy} onClick={async()=>{setBusy(true);try{await run({action:'importClients',clients:preview});setCSV('');setPreview([])}catch{}finally{setBusy(false)}}}>{busy?'Importing…':'Import these contacts'}</Button></>}</section>}
